import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const root = join(here, '..', '..')

const html = readFileSync(join(root, 'public', 'portfolio', 'index.html'), 'utf8')
const outDir = join(root, 'server', 'generated')
mkdirSync(outDir, { recursive: true })
writeFileSync(
  join(outDir, 'portfolio-index.ts'),
  `// Generated by portfolio/scripts/export-html.mjs — rewritten on every portfolio build.
export const PORTFOLIO_INDEX_HTML = ${JSON.stringify(html)}
`,
)
console.log('✓ portfolio index.html exported to server/generated/portfolio-index.ts')
